  os: "linux"
  dist: "xenial"
  arch:
    "arm64"
  language: node_js
  "node_js":
    "14"
  script: "npm run test"
  before_install:
    - wget https://github.com/joan2937/pigpio/archive/master.zip
    - unzip master.zip
    - cd pigpio-master
    - make
    - sudo make install
